services:
  app:
    image: ${ORO_AP_IMAGE:-harborio.oro.cloud/activepieces/activepieces}:${ORO_AP_IMAGE_TAG:-latest}
    hostname: activepieces-app
    restart: unless-stopped
    env_file: .env
    environment:
      AP_CONTAINER_TYPE: APP
      # Absolute paths that match the mounted volumes
      AP_CACHE_PATH: /var/lib/activepieces/cache
      AP_CONFIG_PATH: /var/lib/activepieces/config
    ports:
      - "${AP_PORT:-4200}:4200"
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck"]
    volumes:
      - cache:/var/lib/activepieces/cache
      - config:/var/lib/activepieces/config

  worker:
    image: ${ORO_AP_IMAGE:-harborio.oro.cloud/activepieces/activepieces}:${ORO_AP_IMAGE_TAG:-latest}
    restart: unless-stopped
    env_file: .env
    environment:
      AP_CONTAINER_TYPE: WORKER
      AP_CACHE_PATH: /var/lib/activepieces/cache
      AP_CONFIG_PATH: /var/lib/activepieces/config
      AP_FRONTEND_URL: http://app:${AP_PORT:-4200}
    deploy:
      replicas: 2
    depends_on:
      app:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "healthcheck"]
    volumes:
      - cache:/var/lib/activepieces/cache
      - config:/var/lib/activepieces/config

  redis:
    image: 'redis:7-alpine'
    restart: unless-stopped
    healthcheck:
      test: "[ $$(redis-cli ping) = 'PONG' ]"
      interval: 15s
      timeout: 30s
      start_period: 20s
    volumes:
      - 'redis_data:/data'

  postgres:
    image: postgres:18
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${AP_POSTGRES_DB:-activepieces}
      POSTGRES_USER: ${AP_POSTGRES_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${AP_POSTGRES_PASSWORD:-password}
    healthcheck:
      test: ["CMD", "pg_isready", "-h", "127.0.0.1", "-p", "${AP_POSTGRES_PORT:-5432}", "-U", "${AP_POSTGRES_USERNAME:-postgres}", "-d", "${AP_POSTGRES_DB:-activepieces}"]
      start_period: 60s
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  redis_data:
  postgres_data:
  cache:
  config:
